language: java
dist: bionic
env:
    global:
        - OPENCV_VERSION=4.3.0
        - OPENCV_OPNP_REV=2
git:
  depth: 1
arch:
#  - amd64
  - arm64
os:
  - linux
#  - osx
#  - windows

jobs:
  fast_finish: true
  include:
#  - os: linux
#    arch: amd64
  - os: linux
    arch: arm64
#  - os: osx
addons:
  apt:
    packages:
    - build-essential
    - pkg-config
    - cmake
    - ant
    - maven
    - unzip
    - libgtk-3-dev
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - libv4l-0
    - libv4l-dev
    - libxvidcore-dev
    - libx264-dev
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    - libatlas-base-dev
    - python3-dev
    - python3-numpy
    - libgstreamer1.0-dev
    - libgstreamer-plugins-base1.0-dev
    - libopenblas-dev
    - liblapack-dev
    - libeigen3-dev
    - libmpfrc++-dev

before_script:
    #https://github.com/opencv/opencv/archive/4.3.0.zip
    - mkdir -p opencv && cd opencv && wget https://github.com/opencv/opencv/archive/$OPENCV_VERSION.zip
    - unzip $OPENCV_VERSION.zip && mv opencv-$OPENCV_VERSION opencv-$OPENCV_VERSION-$OPENCV_OPNP_REV && rm *.zip
#    - git clone --branch $OPENCV_VERSION --single-branch --depth 1 \
#               https://github.com/opencv/opencv opencv/opencv-$OPENCV_VERSION
#    - ./create-targets.sh $OPENCV_VERSION-$OPENCV_OPNP_REV
    - ./create-targets.sh $OPENCV_VERSION

script: ./ci/build.sh

#env:
#  - ARCH=x64
#  - ARCH=x32
#  - ARCH=arm64

#jdk:
#  - openjdk8 
#  - oraclejdk11
