language: java
dist: bionic
env:
    global:
        - OPENCV_VERSION=4.3.0
        - OPENCV_OPNP_REV=2
git:
  depth: 1
arch:
#  - amd64
  - arm64
os:
  - linux
#  - osx
#  - windows

jobs:
  fast_finish: true
  include:
#  - os: linux
#    arch: amd64
  - os: linux
    arch: arm64
#  - os: osx
addons:
  apt:
    packages:
    - build-essential
    - pkg-config
    - cmake
    - ant
    - maven
    - unzip
    - libjna-jni
    - libgtk-3-dev
    - libavcodec-dev
    - libavformat-dev
    - libswscale-dev
    - libv4l-0
    - libv4l-dev
    - libxvidcore-dev
    - libx264-dev
    - libjpeg-dev
    - libpng-dev
    - libtiff-dev
    - libatlas-base-dev
    - python3-dev
    - python3-numpy
    - libgstreamer1.0-dev
    - libgstreamer-plugins-base1.0-dev
    - libopenblas-dev
    - liblapack-dev
    - libeigen3-dev
    - libmpfrc++-dev
    # OpenCV
    - opencv
#    - libopencv-features2d4.2
#    - libopencv-imgcodecs4.2
#    - libopencv-imgproc4.2
#    - libopencv-ml4.2
#    - libopencv-objdetect4.2
#    - libopencv-photo4.2
#    - libopencv-shape4.2
#    - libopencv-stitching4.2
#    - libopencv-video4.2
#    - libopencv-videoio4.2
#    - libopencv4.2-jni
#    - libopencv4.2-java
#    - libopencv-viz4.2
#    - python3-opencv

before_script:
    - mkdir -p opencv && cd opencv && wget https://github.com/opencv/opencv/archive/$OPENCV_VERSION.zip
    - unzip $OPENCV_VERSION.zip && rm *.zip
    - cd .. && ./create-targets.sh $OPENCV_VERSION

script: ./ci/build.sh

#env:
#  - ARCH=x64
#  - ARCH=x32
#  - ARCH=arm64

#jdk:
#  - openjdk8 
#  - oraclejdk11
#
notifications:
  email: false

